language: go

go:
  - 1.4
  - 1.5

sudo: required

services:
  - docker

before_install:
  - docker pull dennwc/orientdb:2.1.1
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint

install:
  - go get -t -v ./...

script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -race -v ./...
  - go test -covermode=atomic ./...
