language: go

sudo: required

services:
  - docker

go:
  - 1.4
  - 1.5

env:
  - ORIENT_VERS=2.1.2

matrix:
  include:
    - go: 1.4
      env:
        - ORIENT_VERS=2.1.1
        - ORIENT_VERS=2.0

install:
  - mkdir -p $GOPATH/src/gopkg.in/istreamdata
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/gopkg.in/istreamdata/orientgo.v2
  - export TRAVIS_BUILD_DIR=$GOPATH/src/gopkg.in/istreamdata/orientgo.v2
  - cd $GOPATH/src/gopkg.in/istreamdata/orientgo.v2
  - docker pull dennwc/orientdb:${ORIENT_VERS}
  - go get golang.org/x/tools/cmd/vet
#  - go get golang.org/x/tools/cmd/cover
#  - go get github.com/golang/lint/golint
  - go get -t -v ./...

script:
  - go test -v -race ./...
  - go vet .
  - go vet ./obinary
  - go tool vet -methods=false ./obinary/rw
#  - go test -covermode=atomic ./...
#  - $HOME/gopath/bin/golint .
